version: "2"

linters:
  default: none

  enable:
    - asciicheck
    - bodyclose
    - err113

    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    - cyclop
    - copyloopvar
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - gocritic
